# Generated by Django 4.2.23 on 2025-08-06 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityMeetingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_id', models.CharField(help_text='ERP Document ID for the check-in record', max_length=255)),
                ('customer', models.CharField(help_text='Customer linked to this check-in', max_length=255)),
                ('opportunity', models.CharField(help_text='Opportunity linked to this check-in', max_length=255)),
                ('agenda', models.TextField(blank=True, help_text='Meeting agenda or purpose')),
                ('visited_department', models.CharField(blank=True, help_text='Department visited during the meeting', max_length=255)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person encountered', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from the meeting')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Local timestamp when meeting detail was recorded')),
                ('user', models.ForeignKey(help_text='Django user who performed the check-in', on_delete=django.db.models.deletion.CASCADE, related_name='meeting_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Meeting Detail',
                'verbose_name_plural': 'Opportunity Meeting Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
