# Generated by Django 4.2.23 on 2025-08-14 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_customerlocationupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(choices=[('PUNCH_IN', 'Punch In'), ('PUNCH_OUT_NEAR', 'Punch Out (≤200m)'), ('PUNCH_OUT_FAR', 'Punch Out (>200m)'), ('MEETING_DETAILS', 'Meeting Details Added'), ('LOCATION_UPDATE_APPROVED', 'Customer Location Approved')], max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_txs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
