# Generated by Django 4.2.23 on 2025-08-14 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_energypointtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMergeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_primary_history', to=settings.AUTH_USER_MODEL)),
                ('secondary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_secondary_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usermergehistory',
            constraint=models.UniqueConstraint(fields=('primary_user', 'secondary_user'), name='unique_user_merge'),
        ),
    ]
